name: Build Msys2 Artifact
run-name: ${{ github.actor }} Build Msys artifact.
on:
  push:
    tags:
    - "*"

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      
      - name: MSYS2 setup
        uses: msys2/setup-msys2@v2
        with:
          update: true
          location: D:\
          install: >-
            make
            autotools
            gcc

      - name: Clone corkscrew
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'bryanpkc'
          repository: 'corkscrew'

      - name: Build corkscrew
        shell: msys2 {0}
        run: |
          cd corkscrew
          autoreconf --install
          ./configure
          make
          make install
      
      - name: Create package
        run: |
          New-Item -Path 'artifact' -ItemType Directory
          Compress-Archive -Path D:\msys64 -D artifact\wtp-msys2.zip
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          name: wtb-scoop.${{ github.ref }}.zip
          artifacts: "artifact/wtp-msys2.zip"
      